### PR TITLE
Add a node radar that shows ores/gems/geode nodes on current floor/area

### PR DESCRIPTION
**Pull request by FinalDoom**
I think things are in a good state now. Plus a few more efficiency changes from last PR attempt. Still showing the old changes in the log, but the diffs look correct.

* Node radar, if enabled, shows ores/gems/geode stones near the energy/health bar (works for quarry and volcano too)
* Can restrict which types of nodes are shown in config
* Changed ladder (and node) finding to use location.objects dictionary instead of going through every tile
* Changed event hooks:
* When stones are broken, ladder state is rechecked and node state is updated (faster than doing it on second ticks)
* Most things are set up on warp--sometimes ladders haven't been determined yet, so fall back to second ticks. This either ticks once to when ladders have been determined, or keeps polling like previous behavior until RNG has changed to make ladders show
* Tick event removes itself once a ladder is found

### CODE REVIEW

**Comment by yuri-moens** [comment]
There are some issues with zoom level/UI scale which means the radar can end up behind the health/energy bars. Could you have a look at that?
Also, a toggle button for the radar function would be a nice addition.

**Comment by FinalDoom** [comment]
Good catch. I'll see what I can do about that.

**Comment by FinalDoom** [comment]
Took a while to figure out I could just move things to a different display event to be writing to the UI layer properly for a "hud" element. Should be good now with keybinds and proper scaling

**Comment by yuri-moens** [comment]
Looks great, thanks!

I've reverted the version number back to 1.4.0 seeing as how it was fixed before releasing.

**Comment by FinalDoom** [comment]
Makes sense. I never know what to do with versions XD

**Pull request merged**
